const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const state={diamonds:999999,coins:999999,quality:localStorage.erQuality||'medium',fps:+(localStorage.erFps||60),music:localStorage.erMusic!=='0',sfx:localStorage.erSfx!=='0',hero:localStorage.erHero||'VANGUARD',playing:false};
const heroes=[{n:'VANGUARD',p:'ESCUDO CINÉTICO',d:'Reduz dano recebido por 3s.',c:'◆'},{n:'PHANTOM',p:'PASSO FANTASMA',d:'Fica parcialmente invisível por 2.5s.',c:'◇'},{n:'VOLT',p:'SOBRECARGA',d:'Aumenta velocidade por 4s.',c:'⚡'},{n:'MEDIC',p:'PULSO VITAL',d:'Recupera 35 HP.',c:'✚'}],skins=['NEON GUARD','NIGHT OPS','CYBER EMPEROR','DESERT GHOST'];
function showScreen(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===id))}
function render(){ $('#diamonds').textContent=state.diamonds.toLocaleString('pt-BR');$('#coins').textContent=state.coins.toLocaleString('pt-BR');$('#lobbyChar').textContent=state.hero;$('#heroGrid').innerHTML=heroes.map(h=>'<article class="card"><div class="mini-avatar">'+h.c+'</div><h3>'+h.n+'</h3><small>'+h.p+'</small><p>'+h.d+'</p><button data-hero="'+h.n+'">'+(state.hero===h.n?'SELECIONADO':'SELECIONAR')+'</button></article>').join('');$('#shopGrid').innerHTML=skins.map(s=>'<article class="card"><div class="mini-avatar">◆</div><h3>'+s+'</h3><small>SKIN COSMÉTICA</small><p>Disponível na beta.</p><button data-skin="'+s+'">GRATUITA • BETA</button></article>').join();$('#quality').value=state.quality;$('#fps').value=state.fps;$('#music').checked=state.music;$('#sfx').checked=state.sfx}
$$('.nav').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));$$('.back').forEach(b=>b.onclick=()=>showScreen('lobby'));
document.addEventListener('click',e=>{if(e.target.dataset.hero){state.hero=e.target.dataset.hero;localStorage.erHero=state.hero;render()}if(e.target.dataset.skin)toast('Skin equipada: '+e.target.dataset.skin)});
$('#quality').onchange=e=>{state.quality=e.target.value;localStorage.erQuality=state.quality};$('#fps').onchange=e=>{state.fps=+e.target.value;localStorage.erFps=state.fps};$('#music').onchange=e=>{state.music=e.target.checked;localStorage.erMusic=state.music?'1':'0';if(state.music)audio.start()};$('#sfx').onchange=e=>{state.sfx=e.target.checked;localStorage.erSfx=state.sfx?'1':'0'};$('#reset').onclick=()=>{localStorage.clear();location.reload()};
function toast(t){const x=document.createElement('div');x.textContent=t;x.style='position:fixed;z-index:30;left:50%;top:18%;transform:translateX(-50%);background:#0c1b27;border:1px solid #55d8ff;padding:12px 18px;border-radius:7px';document.body.append(x);setTimeout(()=>x.remove(),1300)}
const audio={ctx:null,osc:null,start(){if(!state.music)return;this.ctx=this.ctx||new (window.AudioContext||window.webkitAudioContext)();if(this.osc)return;this.osc=this.ctx.createOscillator();const g=this.ctx.createGain();this.osc.type='sine';this.osc.frequency.value=110;g.gain.value=.018;this.osc.connect(g).connect(this.ctx.destination);this.osc.start()},shot(){if(!state.sfx)return;this.ctx=this.ctx||new (window.AudioContext||window.webkitAudioContext)();const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='square';o.frequency.setValueAtTime(140,this.ctx.currentTime);o.frequency.exponentialRampToValueAtTime(55,this.ctx.currentTime+.09);g.gain.setValueAtTime(.06,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,this.ctx.currentTime+.1);o.connect(g).connect(this.ctx.destination);o.start();o.stop(this.ctx.currentTime+.1)}};
const canvas=$('#canvas'),ctx=canvas.getContext('2d');let W,H,dpr,raf,last=0,game=null;function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function startGame(){audio.start();$('#game').classList.remove('hidden');$('#result').classList.add('hidden');state.playing=true;game={t:0,px:0,py:0,kills:0,alive:20,ammo:30,zoneR:Math.min(W,H)*.39,bots:[]};for(let i=0;i<19;i++)game.bots.push({x:(Math.random()-.5)*W*1.4,y:(Math.random()-.5)*H*1.1,hp:100,alive:true,spd:12+Math.random()*20,ang:Math.random()*7});$('#score').textContent='0';$('#alive').textContent=20;$('#ammo').textContent='30 / 120';addFeed('Você entrou no campo de batalha.');last=performance.now();raf=requestAnimationFrame(loop)}
function endGame(){state.playing=false;const place=Math.floor(Math.random()*6)+1,k=game.kills,rp=Math.max(12,60-place*5+k*3);$('#place').textContent='#'+place;$('#resultKills').textContent=k;$('#resultRp').textContent='+'+rp;$('#resultTitle').textContent=place===1?'EMPIRE VICTORY':'BOA PARTIDA';$('#games').textContent=+$('#games').textContent+1;$('#kills').textContent=+$('#kills').textContent+k;$('#rankPts').textContent=(1240+rp)+' RP';$('#result').classList.remove('hidden')}
function loop(now){if(!state.playing)return;const dt=Math.min(.04,(now-last)/1000);last=now;game.t+=dt;game.zoneR=Math.max(55,game.zoneR-dt*1.7);game.bots.forEach(b=>{if(!b.alive)return;b.ang+=(Math.random()-.5)*dt*2;b.x+=Math.cos(b.ang)*b.spd*dt;b.y+=Math.sin(b.ang)*b.spd*dt;if(Math.hypot(b.x-game.px,b.y-game.py)<55&&Math.random()<dt*.12)damage()});if(game.t>90||game.alive<=1)endGame();draw();raf=requestAnimationFrame(loop)}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle=state.quality==='high'?'#183c2b':'#102c22';ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W/2-game.px,H/2-game.py);drawMap();ctx.restore();drawZone();drawPlayer()}
function drawMap(){const grid=state.quality==='low'?70:45;ctx.strokeStyle='#ffffff0d';for(let x=-W*2;x<W*2;x+=grid){ctx.beginPath();ctx.moveTo(x,-H*2);ctx.lineTo(x,H*2);ctx.stroke()}for(let y=-H*2;y<H*2;y+=grid){ctx.beginPath();ctx.moveTo(-W*2,y);ctx.lineTo(W*2,y);ctx.stroke()}for(let i=0;i<13;i++){const x=(i*173%900)-450,y=(i*97%700)-350;ctx.fillStyle='#172f27';ctx.fillRect(x,y,85,55);ctx.strokeStyle='#2a5143';ctx.strokeRect(x,y,85,55)}game.bots.forEach(b=>{if(!b.alive)return;ctx.fillStyle='#e35b68';ctx.beginPath();ctx.arc(b.x,b.y,12,0,7);ctx.fill();ctx.fillStyle='#62e0ff';ctx.fillRect(b.x-9,b.y-18,18*(b.hp/100),3)})}
function drawZone(){ctx.save();ctx.fillStyle='#08121d55';ctx.fillRect(0,0,W,H);ctx.globalCompositeOperation='destination-out';ctx.beginPath();ctx.arc(W/2,H/2,game.zoneR,0,7);ctx.fill();ctx.restore();ctx.strokeStyle='#55d8ff88';ctx.lineWidth=3;ctx.beginPath();ctx.arc(W/2,H/2,game.zoneR,0,7);ctx.stroke()}
function drawPlayer(){ctx.fillStyle='#55d8ff';ctx.beginPath();ctx.arc(W/2,H/2,14,0,7);ctx.fill();ctx.fillStyle='#dff9ff';ctx.beginPath();ctx.arc(W/2,H/2-10,7,0,7);ctx.fill()}
function damage(){game.kills++;game.alive=Math.max(1,game.alive-1);$('#score').textContent=game.kills*6;$('#alive').textContent=game.alive;$('#damage').classList.remove('hit');void $('#damage').offsetWidth;$('#damage').classList.add('hit');game.ammo=Math.max(0,game.ammo-1);$('#ammo').textContent=game.ammo+' / 120';audio.shot();addFeed('✦ Abate confirmado +6 RP')}
function addFeed(t){const e=document.createElement('div');e.className='feedline';e.textContent=t;$('#feed').append(e);setTimeout(()=>e.remove(),3500)}
$('#fire').onpointerdown=()=>{if(state.playing)damage()};$('#reload').onclick=()=>{game.ammo=30;$('#ammo').textContent='30 / 120';addFeed('Carregador recarregado.')};$('#skill').onclick=()=>{addFeed(state.hero+' — habilidade ativada!');toast('Habilidade ativada')};$('#heal').onclick=()=>addFeed('Kit médico usado. +25 HP');$('#leave').onclick=()=>{if(confirm('Sair da partida?')){state.playing=false;$('#game').classList.add('hidden');showScreen('lobby')}};$('#again').onclick=()=>startGame();$('#toLobby').onclick=()=>{$('#result').classList.add('hidden');$('#game').classList.add('hidden');showScreen('lobby')};$('#playBtn').onclick=startGame;
let joy={on:false};const joyEl=$('#joy');joyEl.onpointerdown=e=>{joy.on=true;joyEl.setPointerCapture(e.pointerId)};joyEl.onpointermove=e=>{if(!joy.on||!game)return;const r=joyEl.getBoundingClientRect();game.px+=Math.max(-1,Math.min(1,(e.clientX-(r.left+r.width/2))/45))*70/60;game.py+=Math.max(-1,Math.min(1,(e.clientY-(r.top+r.height/2))/45))*70/60};joyEl.onpointerup=()=>{joy.on=false};
(function load(){let p=0;const texts=['CARREGANDO MAPA...','PREPARANDO ARMAS...','SINCRONIZANDO BATALHA...','EMPIRE ROYALE'];const iv=setInterval(()=>{p=Math.min(100,p+Math.random()*22+8);$('#loadFill').style.width=p+'%';$('#loadText').textContent=texts[Math.min(3,Math.floor(p/28))];if(p>=100){clearInterval(iv);setTimeout(()=>{$('#loading').remove();$('#app').classList.remove('hidden');render()},300)}},160)})();